before:
  hooks:
    - go mod tidy

builds:
  - id: beacon-chain
    main: ./cmd/beacon-chain
    binary: beacon-chain
    ldflags:
      #- -s -w -X runtime/version.gitTag={{.Version}} -X runtime/version.gitCommit={{.Commit}} -X runtime/version={{.Date}}
      - -X runtime/version.gitTag={{.Version}} -X runtime/version.gitCommit={{.Commit}} -X runtime/version={{.Date}}
    env:
      - CGO_ENABLED=1
      - CC=arm-linux-gnueabi-gcc
    goos:
      - linux
     # - windows
     # - darwin
    goarch:
      - amd64
     # - arm64

archives:
  - format: tar.gz
    name_template: >-
      {{ .Binary }}-
      {{ .Version }}-
      {{- title .Os }}-
      {{ .Arch }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"