version: 2.1


restore_bazel_cache: &restore_bazel_cache
  restore_cache:
    keys:
      - v4-bazel-cache-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-{{ .Revision }}
      - v4-bazel-cache-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}
      - v4-bazel-cache-{{ .Environment.CIRCLE_JOB }}-main

save_bazel_cache: &save_bazel_cache
  save_cache:
    # Always saving the cache, even in case of failures, helps with completing
    # jobs where the bazel process was killed because it took too long or OOM.
    # Restart the job if you see the bazel server being terminated abruptly.
    when: always
    key: v4-bazel-cache-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-{{ .Revision }}
    paths:
      - /tmp/bazel-cache
      - /tmp/bazel-disk-cache

clean_bazel_cache: &clean_bazel_cache
  run:
    name: Clean Bazel disk cache of files that have not been modified in 30 days
    # mtime is the only time preserved after untaring the cache.
    command: /usr/bin/find /tmp/bazel-disk-cache -mtime +30 -exec rm -v {} \;

# Use a bazelrc file convenient for CI jobs.
set_bazelrc: &set_bazelrc
  run:
    name: Set bazelrc
    command: cat .circleci/bazelrc >> .bazelrc

install_bazel: &install_bazel
  run:
    name: Install bazel
    command: |
      curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.1.0/bazelisk-linux-amd64"
      mkdir -p bin
      mv bazelisk-linux-amd64 bin/bazel
      chmod +x bin/bazel

jobs:
  publish-linux-amd64-beacon-chain-binary:
    docker:
      - image: cimg/base:2023.09
    #resource_class: xlarge
    steps:
      - checkout
      - *install_bazel
      - *restore_bazel_cache
      - *set_bazelrc
      - run: |
          # bin/bazel build --config=release --config=linux_amd64 --define=blst_modern=false //cmd/beacon-chain
          rm -rf /tmp/bazel-cache/output-root/install
          bin/bazel build --config=release --define=blst_modern=false //cmd/beacon-chain
          #cp bazel-bin/cmd/beacon-chain/beacon-chain_/beacon-chain /tmp/beacon-chain-${CIRCLE_TAG}-linux-amd64
          #(cd /tmp && sha256sum beacon-chain-${CIRCLE_TAG}-linux-amd64 > beacon-chain-${CIRCLE_TAG}-linux-amd64.sha256)
          #gpg -o /tmp/beacon-chain-${CIRCLE_TAG}-linux-amd64.sig --default-key 0AE0051D647BA3C1A917AF4072E33E4DF1A5036E --sign --detach-sig /tmp/beacon-chain-${CIRCLE_TAG}-linux-amd64
          #./hack/upload-github-release-asset.sh github_api_token=$TOKEN owner=prysmaticlabs repo=prysm tag=${CIRCLE_TAG} filename=/tmp/beacon-chain-${CIRCLE_TAG}-linux-amd64
          #ls bin
      - *clean_bazel_cache
      - *save_bazel_cache
      
  
  # build-windows-amd64-beacon-chain-binary:
  #   executor: my-executor
  #   #resource_class: xlarge
  #   steps:
  #     - checkout
  #     - setup_remote_docker:
  #         version: 20.10.14
  #         docker_layer_caching: true
  #     - run: |
  #         curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.1.0/bazelisk-linux-amd64"
  #         mkdir -p bin
  #         mv bazelisk-linux-amd64 bin/bazel
  #         chmod +x bin/bazel
  #     - run: |
  #         bin/bazel build --config=release --config=windows_amd64_docker  //cmd/beacon-chain
  #         cp bazel-bin/cmd/beacon-chain/beacon-chain_/beacon-chain.exe bin/beacon-chain-${CIRCLE_TAG}-windows-amd64.exe
  #         ls bin
  #     - persist_to_workspace:
  #         root: bin
  #         paths:
  #           - beacon-chain-${CIRCLE_TAG}-windows-amd64.exe
  
  # build-darwin-amd64-beacon-chain-binary:
  #   executor: my-executor
  #   #resource_class: xlarge
  #   steps:
  #     - checkout
  #     - setup_remote_docker:
  #         version: 20.10.14
  #         docker_layer_caching: true
  #     - run: |
  #         curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.1.0/bazelisk-linux-amd64"
  #         mkdir -p bin
  #         mv bazelisk-linux-amd64 bin/bazel
  #         chmod +x bin/bazel
  #     - run: |
  #         bin/bazel build --config=release --config=osx_amd64_docker  //cmd/beacon-chain
  #         cp bazel-bin/cmd/beacon-chain/beacon-chain_/beacon-chain bin/beacon-chain-${CIRCLE_TAG}-darwin-amd64
  #         ls bin
  #     - persist_to_workspace:
  #         root: bin
  #         paths:
  #           - beacon-chain-${CIRCLE_TAG}-darwin-amd64

  #post-build:
  #  executor: my-executor
  #  steps:
  #    - attach_workspace:
  #        at: /tmp/workspace/bin
  #    - checkout
  #    - run: |
  #        ls /tmp/workspace/bin


workflows:
  release:
    jobs:
      - publish-linux-amd64-beacon-chain-binary
          # filters:
          #   tags:
          #     only: /^circlev.*/
          #     #only: /^v.*/
          #   # branches:
          #   #   ignore: /.*/
      #- build-windows-amd64-beacon-chain-binary
      #- build-darwin-amd64-beacon-chain-binary
      #- post-build:
          #requires:
            #- build-linux-amd64-beacon-chain-binary
            #- build-windows-amd64-beacon-chain-binary
            #- build-darwin-amd64-beacon-chain-binary