version: 2.1

executors:
  my-executor:
    docker:
      - image: cimg/base:2023.09
    working_directory: /tmp/workspace


jobs:
  build-linux-amd64-beacon-chain-binary:
    executor: my-executor
    #resource_class: xlarge
    steps:
      - checkout
      - run: |
          curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.1.0/bazelisk-linux-amd64"
          mkdir -p "bin"
          mv bazelisk-linux-amd64 "${CIRCLE_WORKING_DIRECTORY}/bin/bazel"
          chmod +x "${CIRCLE_WORKING_DIRECTORY}/bin/bazel"
      - run: |
          "${CIRCLE_WORKING_DIRECTORY}/bin/bazel" build --config=release --config=linux_amd64 --define=blst_modern=false //cmd/beacon-chain
          cp bazel-bin/cmd/beacon-chain/beacon-chain_/beacon-chain /tmp/beacon-chain-$CIRCLE_TAG-linux-amd64
      - persist_to_workspace:
          root: /tmp
          paths:
            - beacon-chain-$CIRCLE_TAG-linux-amd64
  post-build:
    executor: my-executor
    steps:
      - attach_workspace:
          at: /tmp
      - checkout
      - run: |
          ls tmp

workflows:
  release:
    jobs:
      - build-linux-amd64-beacon-chain-binary:
          filters:
            tags:
              only: /^circlev.*/
              #only: /^v.*/
      - post-build:
          requires:
            - build-linux-amd64-beacon-chain-binary