version: 2.1

orbs:
  win: circleci/windows@2.4.0


restore_bazel_cache: &restore_bazel_cache
  restore_cache:
    keys:
      - v4-bazel-cache-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-{{ .Revision }}
      - v4-bazel-cache-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}
      - v4-bazel-cache-{{ .Environment.CIRCLE_JOB }}-main

save_bazel_cache: &save_bazel_cache
  save_cache:
    # Always saving the cache, even in case of failures, helps with completing
    # jobs where the bazel process was killed because it took too long or OOM.
    # Restart the job if you see the bazel server being terminated abruptly.
    when: always
    key: v4-bazel-cache-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-{{ .Revision }}
    paths:
      - /tmp/bazel-cache
      - /tmp/bazel-disk-cache

clean_bazel_cache: &clean_bazel_cache
  run:
    name: Clean Bazel disk cache of files that have not been modified in 30 days
    # mtime is the only time preserved after untaring the cache.
    command: /usr/bin/find /tmp/bazel-disk-cache -mtime +30 -exec rm -v {} \;

set_bazelrc: &set_bazelrc
  run:
    name: Set bazelrc
    command: cat .circleci/bazelrc >> .bazelrc

commands:
  setup-bazel:
    parameters:
      platform:
        type: string
        default: "linux-amd64"
      steps:
        - run: |
            curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.1.0/bazelisk-<< parameters.platform >>"
            mkdir -p bin
            mv bazelisk-linux-amd64 bin/bazel
            chmod +x bin/bazel

# install_bazel_linux_amd64: &install_bazel_linux_amd64
#   run:
#     name: Install bazel
#     command: |
#       curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.1.0/bazelisk-linux-amd64"
#       mkdir -p bin
#       mv bazelisk-linux-amd64 bin/bazel
#       chmod +x bin/bazel

# install_bazel_linux_arm64: &install_bazel_linux_arm64
#   run:
#     name: Install bazel
#     command: |
#       curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.1.0/bazelisk-linux-arm64"
#       mkdir -p bin
#       mv bazelisk-linux-arm64 bin/bazel
#       chmod +x bin/bazel

# install_bazel_darwin_amd64: &install_bazel_darwin_amd64
#   run:
#     name: Install bazel
#     command: |
#       curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.1.0/bazelisk-darwin-amd64"
#       mkdir -p bin
#       mv bazelisk-darwin-amd64 bin/bazel
#       chmod +x bin/bazel

# install_bazel_darwin_arm64: &install_bazel_darwin_arm64
#   run:
#     name: Install bazel
#     command: |
#       curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.1.0/bazelisk-darwin-arm64"
#       mkdir -p bin
#       mv bazelisk-darwin-arm64 bin/bazel
#       chmod +x bin/bazel

jobs:
  publish-linux-amd64-beacon-chain-binary:
    docker:
      - image: cimg/base:2023.09
    steps:
      - checkout
      #- *install_bazel_linux_amd64
      - setup-bazel:
          platform: "linux-amd64"
      - *restore_bazel_cache
      - *set_bazelrc
      - run: |
          rm -rf /tmp/bazel-cache/output-root/install
          
          bin/bazel build --config=release --define=blst_modern=false //cmd/beacon-chain //cmd/validator
          
          cp bazel-bin/cmd/beacon-chain/beacon-chain_/beacon-chain /tmp/beacon-chain-${CIRCLE_TAG}-linux-amd64
          cp bazel-bin/cmd/validator/validator_/validator /tmp/validator-${CIRCLE_TAG}-linux-amd64

          (cd /tmp && sha256sum beacon-chain-${CIRCLE_TAG}-linux-amd64 > beacon-chain-${CIRCLE_TAG}-linux-amd64.sha256)
          (cd /tmp && sha256sum validator-${CIRCLE_TAG}-linux-amd64 > validator-${CIRCLE_TAG}-linux-amd64.sha256)

          # TODO(rgeraldes24): replace default key --default-key 0AE0051D647BA3C1A917AF4072E33E4DF1A5036E 
          # TODO(rgeraldes24): remove as soon as the key is available in the machine
          gpg --full-gen-key --batch <(echo "Key-Type: 1"; \
                             echo "Key-Length: 4096"; \
                             echo "Subkey-Type: 1"; \
                             echo "Subkey-Length: 4096"; \
                             echo "Expire-Date: 0"; \
                             echo "Name-Real: Root Superuser"; \
                             echo "Name-Email: root@handbook.westarete.com"; \
                             echo "%no-protection"; )
          gpg -o /tmp/beacon-chain-${CIRCLE_TAG}-linux-amd64.sig --sign --detach-sig /tmp/beacon-chain-${CIRCLE_TAG}-linux-amd64
          gpg -o /tmp/validator-${CIRCLE_TAG}-linux-amd64.sig --sign --detach-sig /tmp/validator-${CIRCLE_TAG}-linux-amd64

          # TODO(rgeraldes24): change owner to 'theQRL' and repo to 'qrysm' and tag to ${CIRCLE_TAG}
          ./hack/upload-github-release-asset.sh github_api_token=$GITHUB_TOKEN owner=rgeraldes24 repo=prysm tag=v0.1.0 filename=/tmp/beacon-chain-${CIRCLE_TAG}-linux-amd64
          ./hack/upload-github-release-asset.sh github_api_token=$GITHUB_TOKEN owner=rgeraldes24 repo=prysm tag=v0.1.0 filename=/tmp/beacon-chain-${CIRCLE_TAG}-linux-amd64.sha256
          ./hack/upload-github-release-asset.sh github_api_token=$GITHUB_TOKEN owner=rgeraldes24 repo=prysm tag=v0.1.0 filename=/tmp/beacon-chain-${CIRCLE_TAG}-linux-amd64.sig
          ./hack/upload-github-release-asset.sh github_api_token=$GITHUB_TOKEN owner=rgeraldes24 repo=prysm tag=v0.1.0 filename=/tmp/validator-${CIRCLE_TAG}-linux-amd64
          ./hack/upload-github-release-asset.sh github_api_token=$GITHUB_TOKEN owner=rgeraldes24 repo=prysm tag=v0.1.0 filename=/tmp/validator-${CIRCLE_TAG}-linux-amd64.sha256
          ./hack/upload-github-release-asset.sh github_api_token=$GITHUB_TOKEN owner=rgeraldes24 repo=prysm tag=v0.1.0 filename=/tmp/validator-${CIRCLE_TAG}-linux-amd64.sig
      - *clean_bazel_cache
      - *save_bazel_cache

  publish-linux-arm64-beacon-chain-binary:
    machine:
      image: ubuntu-2204:2023.07.1
    resource_class: arm.medium
    steps:
      - checkout
      #- *install_bazel_linux_arm64
      - setup-bazel:
          platform: "linux-arm64"
      - *restore_bazel_cache
      - *set_bazelrc
      - run: |
          rm -rf /tmp/bazel-cache/output-root/install
          
          bin/bazel build --config=release //cmd/beacon-chain //cmd/validator
          
          cp bazel-bin/cmd/beacon-chain/beacon-chain_/beacon-chain /tmp/beacon-chain-${CIRCLE_TAG}-linux-arm64
          cp bazel-bin/cmd/validator/validator_/validator /tmp/validator-${CIRCLE_TAG}-linux-arm64

          (cd /tmp && sha256sum beacon-chain-${CIRCLE_TAG}-linux-arm64 > beacon-chain-${CIRCLE_TAG}-linux-arm64.sha256)
          (cd /tmp && sha256sum validator-${CIRCLE_TAG}-linux-arm64 > validator-${CIRCLE_TAG}-linux-arm64.sha256)

          # TODO(rgeraldes24): replace default key --default-key 0AE0051D647BA3C1A917AF4072E33E4DF1A5036E 
          # TODO(rgeraldes24): remove as soon as the key is available in the machine
          gpg --full-gen-key --batch <(echo "Key-Type: 1"; \
                             echo "Key-Length: 4096"; \
                             echo "Subkey-Type: 1"; \
                             echo "Subkey-Length: 4096"; \
                             echo "Expire-Date: 0"; \
                             echo "Name-Real: Root Superuser"; \
                             echo "Name-Email: root@handbook.westarete.com"; \
                             echo "%no-protection"; )
          gpg -o /tmp/beacon-chain-${CIRCLE_TAG}-linux-arm64.sig --sign --detach-sig /tmp/beacon-chain-${CIRCLE_TAG}-linux-arm64
          gpg -o /tmp/validator-${CIRCLE_TAG}-linux-arm64.sig --sign --detach-sig /tmp/validator-${CIRCLE_TAG}-linux-arm64

          # TODO(rgeraldes24): change owner to 'theQRL' and repo to 'qrysm' and tag to ${CIRCLE_TAG}
          ./hack/upload-github-release-asset.sh github_api_token=$GITHUB_TOKEN owner=rgeraldes24 repo=prysm tag=v0.1.0 filename=/tmp/beacon-chain-${CIRCLE_TAG}-linux-arm64
          ./hack/upload-github-release-asset.sh github_api_token=$GITHUB_TOKEN owner=rgeraldes24 repo=prysm tag=v0.1.0 filename=/tmp/beacon-chain-${CIRCLE_TAG}-linux-arm64.sha256
          ./hack/upload-github-release-asset.sh github_api_token=$GITHUB_TOKEN owner=rgeraldes24 repo=prysm tag=v0.1.0 filename=/tmp/beacon-chain-${CIRCLE_TAG}-linux-arm64.sig
          ./hack/upload-github-release-asset.sh github_api_token=$GITHUB_TOKEN owner=rgeraldes24 repo=prysm tag=v0.1.0 filename=/tmp/validator-${CIRCLE_TAG}-linux-arm64
          ./hack/upload-github-release-asset.sh github_api_token=$GITHUB_TOKEN owner=rgeraldes24 repo=prysm tag=v0.1.0 filename=/tmp/validator-${CIRCLE_TAG}-linux-arm64.sha256
          ./hack/upload-github-release-asset.sh github_api_token=$GITHUB_TOKEN owner=rgeraldes24 repo=prysm tag=v0.1.0 filename=/tmp/validator-${CIRCLE_TAG}-linux-arm64.sig
      #- *clean_bazel_cache
      #- *save_bazel_cache

  publish-darwin-amd64-beacon-chain-binary:
    macos:
      xcode: 14.2.0
    resource_class: macos.x86.medium.gen2
    steps:
      - checkout
      #- *install_bazel_darwin_amd64
      - setup-bazel:
          platform: "darwin-amd64"
      - *restore_bazel_cache
      - *set_bazelrc
      - run: |
          rm -rf /tmp/bazel-cache/output-root/install
          
          bin/bazel build --config=release //cmd/beacon-chain //cmd/validator
          
          cp bazel-bin/cmd/beacon-chain/beacon-chain_/beacon-chain /tmp/beacon-chain-${CIRCLE_TAG}-darwin-amd64
          cp bazel-bin/cmd/validator/validator_/validator /tmp/validator-${CIRCLE_TAG}-darwin-amd64

          (cd /tmp && shasum -a 256 beacon-chain-${CIRCLE_TAG}-darwin-amd64 > beacon-chain-${CIRCLE_TAG}-darwin-amd64.sha256)
          (cd /tmp && shasum -a 256 validator-${CIRCLE_TAG}-darwin-amd64 > validator-${CIRCLE_TAG}-darwin-amd64.sha256)

          # TODO(rgeraldes24): replace default key --default-key 0AE0051D647BA3C1A917AF4072E33E4DF1A5036E 
          # TODO(rgeraldes24): remove as soon as the key is available in the machine
          gpg --full-gen-key --batch <(echo "Key-Type: 1"; \
                             echo "Key-Length: 4096"; \
                             echo "Subkey-Type: 1"; \
                             echo "Subkey-Length: 4096"; \
                             echo "Expire-Date: 0"; \
                             echo "Name-Real: Root Superuser"; \
                             echo "Name-Email: root@handbook.westarete.com"; \
                             echo "%no-protection"; )
          gpg -o /tmp/beacon-chain-${CIRCLE_TAG}-darwin-amd64.sig --sign --detach-sig /tmp/beacon-chain-${CIRCLE_TAG}-darwin-amd64
          gpg -o /tmp/validator-${CIRCLE_TAG}-darwin-amd64.sig --sign --detach-sig /tmp/validator-${CIRCLE_TAG}-darwin-amd64

          # TODO(rgeraldes24): change owner to 'theQRL' and repo to 'qrysm' and tag to ${CIRCLE_TAG}
          ./hack/upload-github-release-asset.sh github_api_token=$GITHUB_TOKEN owner=rgeraldes24 repo=prysm tag=v0.1.0 filename=/tmp/beacon-chain-${CIRCLE_TAG}-darwin-amd64
          ./hack/upload-github-release-asset.sh github_api_token=$GITHUB_TOKEN owner=rgeraldes24 repo=prysm tag=v0.1.0 filename=/tmp/beacon-chain-${CIRCLE_TAG}-darwin-amd64.sha256
          ./hack/upload-github-release-asset.sh github_api_token=$GITHUB_TOKEN owner=rgeraldes24 repo=prysm tag=v0.1.0 filename=/tmp/beacon-chain-${CIRCLE_TAG}-darwin-amd64.sig
          ./hack/upload-github-release-asset.sh github_api_token=$GITHUB_TOKEN owner=rgeraldes24 repo=prysm tag=v0.1.0 filename=/tmp/validator-${CIRCLE_TAG}-darwin-amd64
          ./hack/upload-github-release-asset.sh github_api_token=$GITHUB_TOKEN owner=rgeraldes24 repo=prysm tag=v0.1.0 filename=/tmp/validator-${CIRCLE_TAG}-darwin-amd64.sha256
          ./hack/upload-github-release-asset.sh github_api_token=$GITHUB_TOKEN owner=rgeraldes24 repo=prysm tag=v0.1.0 filename=/tmp/validator-${CIRCLE_TAG}-darwin-amd64.sig
      - *clean_bazel_cache
      - *save_bazel_cache

  publish-darwin-arm64-beacon-chain-binary:
    macos:
      xcode: 14.2.0
    resource_class: macos.m1.medium.gen1
    steps:
      - checkout
      #- *install_bazel_darwin_arm64
      - setup-bazel:
          platform: "darwin-arm64"
      - *restore_bazel_cache
      - *set_bazelrc
      - run: |
          rm -rf /tmp/bazel-cache/output-root/install
          
          bin/bazel build --config=release //cmd/beacon-chain //cmd/validator
          
          cp bazel-bin/cmd/beacon-chain/beacon-chain_/beacon-chain /tmp/beacon-chain-${CIRCLE_TAG}-darwin-arm64
          cp bazel-bin/cmd/validator/validator_/validator /tmp/validator-${CIRCLE_TAG}-darwin-arm64

          (cd /tmp && shasum -a 256 beacon-chain-${CIRCLE_TAG}-darwin-arm64 > beacon-chain-${CIRCLE_TAG}-darwin-arm64.sha256)
          (cd /tmp && shasum -a 256 validator-${CIRCLE_TAG}-darwin-arm64 > validator-${CIRCLE_TAG}-darwin-arm64.sha256)

          # TODO(rgeraldes24): replace default key --default-key 0AE0051D647BA3C1A917AF4072E33E4DF1A5036E 
          # TODO(rgeraldes24): remove as soon as the key is available in the machine
          gpg --full-gen-key --batch <(echo "Key-Type: 1"; \
                             echo "Key-Length: 4096"; \
                             echo "Subkey-Type: 1"; \
                             echo "Subkey-Length: 4096"; \
                             echo "Expire-Date: 0"; \
                             echo "Name-Real: Root Superuser"; \
                             echo "Name-Email: root@handbook.westarete.com"; \
                             echo "%no-protection"; )
          gpg -o /tmp/beacon-chain-${CIRCLE_TAG}-darwin-arm64.sig --sign --detach-sig /tmp/beacon-chain-${CIRCLE_TAG}-darwin-arm64
          gpg -o /tmp/validator-${CIRCLE_TAG}-darwin-arm64.sig --sign --detach-sig /tmp/validator-${CIRCLE_TAG}-darwin-arm64

          # TODO(rgeraldes24): change owner to 'theQRL' and repo to 'qrysm' and tag to ${CIRCLE_TAG}
          ./hack/upload-github-release-asset.sh github_api_token=$GITHUB_TOKEN owner=rgeraldes24 repo=prysm tag=v0.1.0 filename=/tmp/beacon-chain-${CIRCLE_TAG}-darwin-arm64
          ./hack/upload-github-release-asset.sh github_api_token=$GITHUB_TOKEN owner=rgeraldes24 repo=prysm tag=v0.1.0 filename=/tmp/beacon-chain-${CIRCLE_TAG}-darwin-arm64.sha256
          ./hack/upload-github-release-asset.sh github_api_token=$GITHUB_TOKEN owner=rgeraldes24 repo=prysm tag=v0.1.0 filename=/tmp/beacon-chain-${CIRCLE_TAG}-darwin-arm64.sig
          ./hack/upload-github-release-asset.sh github_api_token=$GITHUB_TOKEN owner=rgeraldes24 repo=prysm tag=v0.1.0 filename=/tmp/validator-${CIRCLE_TAG}-darwin-arm64
          ./hack/upload-github-release-asset.sh github_api_token=$GITHUB_TOKEN owner=rgeraldes24 repo=prysm tag=v0.1.0 filename=/tmp/validator-${CIRCLE_TAG}-darwin-arm64.sha256
          ./hack/upload-github-release-asset.sh github_api_token=$GITHUB_TOKEN owner=rgeraldes24 repo=prysm tag=v0.1.0 filename=/tmp/validator-${CIRCLE_TAG}-darwin-arm64.sig
      - *clean_bazel_cache
      - *save_bazel_cache

  # publish-windows-amd64-beacon-chain-binary:
  #   executor:
  #     name: win/default
  #     shell: powershell.exe
  #   #resource_class: xlarge
  #   steps:
  #     - checkout
  #     - run: choco install bazel
  #     - run: bazel build --config=release //cmd/beacon-chain //cmd/validator

      # - *install_bazel_linux_amd64
      # - *restore_bazel_cache
      # - *set_bazelrc
      # - run: |
      #     rm -rf /tmp/bazel-cache/output-root/install
          
      #     bin/bazel build --config=release --config=windows_amd64_docker //cmd/beacon-chain //cmd/validator
          
      #     cp bazel-bin/cmd/beacon-chain/beacon-chain_/beacon-chain.exe /tmp/beacon-chain-${CIRCLE_TAG}-windows-amd64.exe
      #     cp bazel-bin/cmd/validator/validator_/validator.exe /tmp/validator-${CIRCLE_TAG}-windows-amd64.exe

      #     (cd /tmp && sha256sum beacon-chain-${CIRCLE_TAG}-windows-amd64.exe > beacon-chain-${CIRCLE_TAG}-windows-amd64.exe.sha256)
      #     (cd /tmp && sha256sum validator-${CIRCLE_TAG}-windows-amd64.exe > validator-${CIRCLE_TAG}-windows-amd64.exe.sha256)

      #     # TODO(rgeraldes24): replace default key --default-key 0AE0051D647BA3C1A917AF4072E33E4DF1A5036E 
      #     # TODO(rgeraldes24): remove as soon as the key is available in the machine
      #     gpg --full-gen-key --batch <(echo "Key-Type: 1"; \
      #                        echo "Key-Length: 4096"; \
      #                        echo "Subkey-Type: 1"; \
      #                        echo "Subkey-Length: 4096"; \
      #                        echo "Expire-Date: 0"; \
      #                        echo "Name-Real: Root Superuser"; \
      #                        echo "Name-Email: root@handbook.westarete.com"; \
      #                        echo "%no-protection"; )
      #     gpg -o /tmp/beacon-chain-${CIRCLE_TAG}-windows-amd64.exe.sig --sign --detach-sig /tmp/beacon-chain-${CIRCLE_TAG}-windows-amd64.exe
      #     gpg -o /tmp/validator-${CIRCLE_TAG}-windows-amd64.exe.sig --sign --detach-sig /tmp/validator-${CIRCLE_TAG}-windows-amd64.exe

      #     # TODO(rgeraldes24): change owner to 'theQRL' and repo to 'qrysm' and tag to ${CIRCLE_TAG}
      #     ./hack/upload-github-release-asset.sh github_api_token=$GITHUB_TOKEN owner=rgeraldes24 repo=prysm tag=v0.1.0 filename=/tmp/beacon-chain-${CIRCLE_TAG}-windows-amd64.exe
      #     ./hack/upload-github-release-asset.sh github_api_token=$GITHUB_TOKEN owner=rgeraldes24 repo=prysm tag=v0.1.0 filename=/tmp/beacon-chain-${CIRCLE_TAG}-windows-amd64.exe.sha256
      #     ./hack/upload-github-release-asset.sh github_api_token=$GITHUB_TOKEN owner=rgeraldes24 repo=prysm tag=v0.1.0 filename=/tmp/beacon-chain-${CIRCLE_TAG}-windows-amd64.exe.sig
      #     ./hack/upload-github-release-asset.sh github_api_token=$GITHUB_TOKEN owner=rgeraldes24 repo=prysm tag=v0.1.0 filename=/tmp/validator-${CIRCLE_TAG}-windows-amd64
      #     ./hack/upload-github-release-asset.sh github_api_token=$GITHUB_TOKEN owner=rgeraldes24 repo=prysm tag=v0.1.0 filename=/tmp/validator-${CIRCLE_TAG}-windows-amd64.exe.sha256
      #     ./hack/upload-github-release-asset.sh github_api_token=$GITHUB_TOKEN owner=rgeraldes24 repo=prysm tag=v0.1.0 filename=/tmp/validator-${CIRCLE_TAG}-windows-amd64.exe.sig
      # - *clean_bazel_cache
      # - *save_bazel_cache

workflows:
  release:
    jobs:
      - publish-linux-amd64-beacon-chain-binary
      - publish-linux-arm64-beacon-chain-binary
      - publish-darwin-amd64-beacon-chain-binary
      - publish-darwin-arm64-beacon-chain-binary
      #- publish-windows-amd64-beacon-chain-binary
          # filters:
          #   tags:
          #     only: /^circlev.*/
          #     #only: /^v.*/
          #   # branches:
          #   #   ignore: /.*/