name: release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install bazelisk
        run: |
          curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.1.0/bazelisk-linux-amd64"
          mkdir -p "${GITHUB_WORKSPACE}/bin/"
          mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
          chmod +x "${GITHUB_WORKSPACE}/bin/bazel"

      - name: Build Linux amd64 artifacts
        run: |
          "${GITHUB_WORKSPACE}/bin/bazel" clean
          "${GITHUB_WORKSPACE}/bin/bazel" build --config=release --config=linux_amd64 --define=blst_modern=false //cmd/beacon-chain //cmd/validator //cmd/client-stats //cmd/prysmctl
          cp bazel-bin/cmd/beacon-chain/beacon-chain_/beacon-chain /tmp/beacon-chain-$GITHUB_REF_NAME-linux-amd64

      - name: Upload artifacts to github release page
        run: |
          ./hack/upload-github-release-asset.sh github_api_token=$TOKEN_GITHUB owner=rgeraldes24 repo=prysm tag=$GITHUB_REF_NAME filename=/tmp/beacon-chain-$GITHUB_REF_NAME-linux-amd64      
